version: "3.9"
services:
  landing:
    restart: always
    image: ghcr.io/mechaflex/landing-page:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`drake.ee`,`www.drake.ee`)"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls.certresolver=myresolver"